### ISSUE TITLE
Check more french caracters

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-sanitize-filename#8]
array('/À/','/Á/','/Â/','/Ã/','/Ä/','/Å/','/Ç/','/È/','/É/','/Ê/','/Ë/','/Ì/','/Í/','/Î/','/Ï/','/Ò/','/Ó/','/Ô/','/Õ/','/Ö/','/Ù/','/Ú/','/Û/','/Ü/','/Ý/','/à/','/á/','/â/','/ã/','/ä/','/å/','/ç/','/è/','/é/','/ê/','/ë/','/ì/','/í/','/î/','/ï/','/ð/','/ò/','/ó/','/ô/','/õ/','/ö/','/ù/','/ú/','/û/','/ü/','/ý/','/ÿ/', '/©/');

**Comment by meneldil** [comment]
Hi, I wanted to know if this improvement will be added?
Indeed, I had a client who used images with these characters not recognized by the plugin ("noël" or "août" for example).

**Comment by MaximeCulea** [comment]
Hello @meneldil,
Thank you for the comment.
I will be adding this soon.

**Comment by meneldil** [comment]
Super ! I look forward.
Thank you for this great plugin! :)

**Comment by MaximeCulea** [comment]
Hey @meneldil, 

So here we are, version [2.0.6](https://github.com/BeAPI/bea-sanitize-filename/releases/tag/2.0.6) and on [wp.org](https://fr.wordpress.org/plugins/bea-sanitize-filename)!

Thank you for waiting, I came from holidays ;)

**Comment by meneldil** [comment]
Champagne ! :)

**Comment by MaximeCulea** [comment]
🍾

**Comment by ajoah** [comment]
Hi @MaximeCulea,
Sorry but i don't understand the purpose of this patch.  (https://github.com/BeAPI/bea-sanitize-filename/commit/54a09444afe0407844fe99776d7750ec7e719c9d)
Accents are already replaced by non accented characters by the `sanitize_title` function.
Moreover `sanitize_file_name_chars` filter remove completely the characters so all accented characters are removed from filename  (instead of replaced).
On the other hand if file hasn't an extension, indeed the filename is returned by `bea_sanitize_file_name` before the use of `sanitize_title` (but it is normally not possible to upload a file without extension)

So to resume : 

v2.0.5 : 
- `noël.jpg` => `noel.jpg`
- `noël` => `noël`

v2.0.6
- `noël.jpg` => `nol.jpg`
- `noël` => `nol`

**Comment by MaximeCulea** [comment]
@ajoah Thank you for reaching out us.

This commit attend to add more accentued caracters which are not handeled.

If you have an issue with the 2.0.6 which includes a lot of features/changes and PR, please open a new issue.

Thank you for your understanding.
